theme: minima
title: Book of One-liners
author: Nicholas Kajoh

twitter_username: nicholaskajoh
github_username:  nicholaskajoh

header_pages:
  - languages/Python.md
  - languages/JavaScript.md
  - languages/Java.md
  - contribute.md
