theme: minima
title: Book of One-liners
author: Nicholas Kajoh

twitter_username: nicholaskajoh
github_username:  nicholaskajoh

header_pages:
  - language/Python.md
  - language/JavaScript.md
  - language/Java.md
  - contribute.md
